TELEGRAM_TOKEN = "part1:part2"
API_URL = "https://www.example.com"

GITHUB_ACCESS_TOKEN = "github_token"
GITHUB_REPO_NAME = "repo_name"
GITHUB_ACCOUNT_USERNAME = "username"
GITHUB_ACCESS_TOKEN_2 = "github_token"
GITHUB_REPO_NAME_2 = "repo_name"
GITHUB_ACCOUNT_USERNAME_2 = "username"
GITHUB_ACCOUNT_EMAIL = "email"
